---
- name: Gather all available z/os facts
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks: 
  - name: Return all available z/os facts
    ibm.ibm.zos.core.zos_gather_facts:
      gather_subset: sys
      register: zos_facts

  - name: Debug z/os facts
    ansible.builtin.debug:
      var: zos_facts